version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: accumulation_db
    ports:
      - "5433:5433"
    env_file:
      - .env
    volumes:
      - postgres-data:/data/postgres-acc
    command: -p 5433

volumes:
  postgres-data: